services:
  - type: web
    name: jobpulse
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: N8N_HOST
        sync: false

      - key: WEBHOOK_URL
        sync: false

      - key: N8N_PROTOCOL
        value: https

      - key: N8N_PORT
        value: "10000"

      - key: N8N_SECURE_COOKIE
        value: "false"

      - key: N8N_RUNNERS_ENABLED
        value: "false"

      - key: TZ
        value: Asia/Kolkata

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata